### Generated by Winemaker 0.8.4
###
### Invocation command line was
### /opt/local/bin/winemaker cdtoimg.sln


SRCDIR                = .
SUBDIRS               =
DLLS                  =
LIBS                  =
EXES                  = cdtoimg.exe



### Common settings

CEXTRA                = -O0 -W  \
			-mno-cygwin
CXXEXTRA              = -O0 -W 
RCEXTRA               =
DEFINES               = -DWIN32 -D_DEBUG -D_CONSOLE 
INCLUDE_PATH          =
DLL_PATH              =
DLL_IMPORTS           =
LIBRARY_PATH          =
LIBRARIES             =


### cdtoimg.exe sources and settings

cdtoimg_exe_MODULE    = cdtoimg.exe
cdtoimg_exe_C_SRCS    =
cdtoimg_exe_CXX_SRCS  = FloatUtils.cpp \
			cdtoimg.cpp
cdtoimg_exe_RC_SRCS   =
cdtoimg_exe_LDFLAGS   = -mwindows \
			-mno-cygwin
cdtoimg_exe_ARFLAGS   =
cdtoimg_exe_DLL_PATH  =
cdtoimg_exe_DLLS      = odbc32 \
			ole32 \
			oleaut32 \
			winspool \
			odbccp32
cdtoimg_exe_LIBRARY_PATH=
cdtoimg_exe_LIBRARIES = uuid

cdtoimg_exe_OBJS      = $(cdtoimg_exe_C_SRCS:.c=.o) \
			$(cdtoimg_exe_CXX_SRCS:.cpp=.o) \
			$(cdtoimg_exe_RC_SRCS:.rc=.res)



### Global source lists

C_SRCS                = $(cdtoimg_exe_C_SRCS)
CXX_SRCS              = $(cdtoimg_exe_CXX_SRCS)
RC_SRCS               = $(cdtoimg_exe_RC_SRCS)


### Tools

CC = winegcc
CXX = wineg++
RC = wrc
AR = ar


### Generic targets

all: $(SUBDIRS) $(DLLS:%=%.so) $(LIBS) $(EXES)

### Build rules

.PHONY: all clean dummy

$(SUBDIRS): dummy
	@cd $@ && $(MAKE)

# Implicit rules

.SUFFIXES: .cpp .cxx .rc .res
DEFINCL = $(INCLUDE_PATH) $(DEFINES) $(OPTIONS)

.c.o:
	$(CC) -c $(CFLAGS) $(CEXTRA) $(DEFINCL) -o $@ $<

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(CXXEXTRA) $(DEFINCL) -o $@ $<

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(CXXEXTRA) $(DEFINCL) -o $@ $<

.rc.res:
	$(RC) $(RCFLAGS) $(RCEXTRA) $(DEFINCL) -fo$@ $<

# Rules for cleaning

CLEAN_FILES     = y.tab.c y.tab.h lex.yy.c core *.orig *.rej \
                  \\\#*\\\# *~ *% .\\\#*

clean:: $(SUBDIRS:%=%/__clean__) $(EXTRASUBDIRS:%=%/__clean__)
	$(RM) $(CLEAN_FILES) $(RC_SRCS:.rc=.res) $(C_SRCS:.c=.o) $(CXX_SRCS:.cpp=.o)
	$(RM) $(DLLS:%=%.so) $(LIBS) $(EXES) $(EXES:%=%.so)

$(SUBDIRS:%=%/__clean__): dummy
	cd `dirname $@` && $(MAKE) clean

$(EXTRASUBDIRS:%=%/__clean__): dummy
	-cd `dirname $@` && $(RM) $(CLEAN_FILES)

### Target specific build rules
DEFLIB = $(LIBRARY_PATH) $(LIBRARIES) $(DLL_PATH) $(DLL_IMPORTS:%=-l%)

$(cdtoimg_exe_MODULE): $(cdtoimg_exe_OBJS)
	$(CXX) $(cdtoimg_exe_LDFLAGS) -o $@ $(cdtoimg_exe_OBJS) $(cdtoimg_exe_LIBRARY_PATH) $(cdtoimg_exe_DLL_PATH) $(DEFLIB) $(cdtoimg_exe_DLLS:%=-l%) $(cdtoimg_exe_LIBRARIES:%=-l%)


